#!/bin/sh

# usage:
#
# sudo ./sync
# sudo ./sync gentoo

set -eu

REPO="$(dirname "$(realpath "$0")")"

PREFIX="${1:-''}"

install_dir() {
    true
}

install_file() {
    prefix="$1"
    path="$5"

    if [ -f "$path" ]; then
        echo cp "$path" "$REPO/$prefix$path"
             cp "$path" "$REPO/$prefix$path"
    else
        echo "Not found: $path"
    fi
}

. "$REPO/files.sh"
